### ISSUE TITLE
Solaris error CRAN (something with ff)

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tabplot#14]
Mail from Prof Ripley:

See https://cran.r-project.org/web/checks/check_results_tabplot.html

The Solaris failure is fairly recent: it worked on Jan 20.  Please correct ASAP and before Feb 26 to safely retain the package on CRAN.

```
checking examples ... ERROR
Running examples in ‘tabplot-Ex.R’ failed
The error most likely occurred in:

> ### Name: -.tabplot
> ### Title: Compare two tableplots (experimental)
> ### Aliases: -.tabplot
>
> ### ** Examples
>
> # load diamonds dataset from ggplot2
> require(ggplot2)
Loading required package: ggplot2
> data(diamonds)
>
> # calculate normalized prices to be used as sample probabilities
> price.norm <- with(diamonds, price / max(diamonds$price))
>
> # draw samples
> exp.diamonds <- diamonds[sample(1:nrow(diamonds), size=10000, prob=price.norm, replace=TRUE),]
> chp.diamonds <- diamonds[sample(1:nrow(diamonds), size=10000, prob=1-price.norm, replace=TRUE),]
>
> tp1 <- tableplot(exp.diamonds)
Error in ff(initdata = initdata, length = length, levels = levels, ordered = ordered, :
  write error
Calls: tableplot ... tablePrepare -> lapply -> FUN -> clone -> clone.ff -> assign -> ff
Execution halted
```

@edwindj Any ideas?

**Comment by latterner-andrew** [comment]
Hello,

I was wondering if there was any plans to fix this error so that it will be available via CRAN at some point in the future?

Thanks

**Comment by mtennekes** [comment]
Haven't got a f* clue how to fix this, and moreover, how to test it (since it only seems to occur with Solaris). Any ideas @edwindj  (or maybe @jwijffels) ? The clone function is called only once in tabplot: https://github.com/mtennekes/tabplot/blob/master/R/subset_data.R#L4

**Comment by jwijffels** [comment]
if it says write error, you either don't have rights to write on a folder, the disk is full or there is a finaliser problem
rhub has a solaris variant - tried it a few times with some other packages with C++ code in there - although it does not always seem to give similar results as cran, you could try it in the hope it gives similar r cmd check results as cran

**Comment by mtennekes** [comment]
Strange, since tabplot only uses ff functions and doesn't contain any C code. Maybe there were problems with CRAN's solaris test environment? I see Jeroen has tutorial on how to test R packages on solaris https://github.com/jeroen/solarisvm, but unfortunately, I don't have time for all that.

Suggestions on how to improve the code are welcome.

**Comment by edwindj** [comment]
I tried to reproduce the error with rhub
```r
rhub::check_for_cran(platforms = "solaris-x86-patched")
```
but that runs fine:

https://builder.r-hub.io/status/tabplot_1.3-2.tar.gz-414564447dee43999ecbb5cd353d0b40

Not sure what our options are...

**Comment by edwindj** [comment]
Strange: skimming the output of `rhub` I noticed that the checking phase is not completed because of an aspell UTF-8 error. It is unclear to me if the example code has been run or not.

**Comment by mtennekes** [comment]
Strange indeed. The aspell error is probably a general one. Email to CRAN has been sent.

**Comment by topepo** [comment]
Any progress on this (CRAN response or otherwise)? Is there anything that we can do to help?

**Comment by mtennekes** [comment]
No response from CRAN yet... :(

**Comment by topepo** [comment]
They almost never respond (esp if BDR wrote the message). 

Have you reached out to the `ff` maintainer in case they have an idea as to what that message is about?

**Comment by mtennekes** [comment]
Reminder sent to CRAN...

**Comment by mtennekes** [comment]
Response from CRAN can be very fast if it is K... :)
He suggested to resubmit.
Done.

**Comment by mtennekes** [comment]
"Thanks, on its way to CRAN.

Best,
Uwe Ligges"

**Comment by jwijffels** [comment]
looks like the package still fails on solaris: https://cran.r-project.org/web/checks/check_results_tabplot.html
my adivse is to look at the arguments provided at
`options()[grepl("^ff", names(options()))]`

**Comment by mtennekes** [comment]
Damn.

Thanks for the advice, Jan. The strange thing to be is that `ff` and `ffbase` run on Solaris without errors. They surely contain examples that write to `options()$fftempdir` as well?

**Comment by jwijffels** [comment]
might also be that too many ff files are open, so meaning that you need to close files (close.ff) which you no longer need. that's why you have these finaliser options in ff. 
normally files are closed when your R session is closed but maybe in that same R session you have too many files open (as in more than your os - in particular solaris can handle). so clean up intermediate calculations with ff with close.ff

**Comment by jwijffels** [comment]
If you run this code, you get the same write error if you have too many files open

```
require(ff)
x <- list()
for(i in 1:100000){
  print(i)
  x[[i]] <- ff(rnorm(10))
  open(x[[i]] )
  #close(x[[i]])
}
```

**Comment by mtennekes** [comment]
If I understand correctly, the temp ff files will not be deleted after `close`, but they will be removed when the ff object is removed, right?

I closed the internal ff vectors (https://github.com/mtennekes/tabplot/commit/b2eabd168424c055f9c73e12f549293bb6241abb)

@edwindj Could you please review and test this ASAP? I don't fully understand yet when ff objects are closed automatically. I created a little test script, see https://github.com/mtennekes/tabplot/blob/master/sandbox/ff_memory_bug.R

When I resubmit to CRAN, I want to make sure everything works properly. If not, tabplot might be blacklisted on CRAN forever;-)

**Comment by jwijffels** [comment]
About line 1 (ff temp files what happens if you remove them). That is documented in the finalizer argument of ?ff. It depends on where you have put the files (in temp directory or another directory).
In your case, for fixing your bug, you just need to make sure every file is closed when you no longer need it internally in your functions.

**Comment by mtennekes** [comment]
Thx!

I think all ff objects are correctly closed. Is there any way to check whether the ff files in the tmp directory are pointed by ff objects that are not properly closed?

**Comment by jwijffels** [comment]
Not that I know of

**Comment by edwindj** [comment]
`rhub::check_on_solars()` does not generate errors, so in the dark on the issues with the CRAN-solaris machine.

**Comment by mtennekes** [comment]
Could it be that the CRAN-solaris machine has less memory than needed to run the current examples in which the ff objects are not closed properly (as @jwijffels wrote above)? If that is the case, it would explain why the machine used by `rhub::check_on_solars` does not generate errors.

If this is indeed the problem, then the question is, whether the commits I made solve it. @edwindj could you check?

**Comment by jwijffels** [comment]
I think that is the most plausible scenario, that the Solaris machine has put limits on the number of available open files in order to avoid that other processes which run at the same time on that machine also start failing because of this package. Given that https://github.com/mtennekes/tabplot/issues/14#issuecomment-489771924 gives the same error as the CRAN check page shows, having too much open files is the problem of this package.

**Comment by mtennekes** [comment]
CRAN 1.3-3 released yesterday, looking good so far: https://cran.r-project.org/web/checks/check_results_tabplot.html
